### ISSUE TITLE
Typo in demo site

### ISSUE THREAD

**Issue by ShaddyDC** [Coderior/lovingmemory#2]
Hello, I was looking over the demo site and noticed in [this line](https://github.com/Coderior/lovingmemory/blob/00f22b1635415d0a916b86cd81f736640ac0bc7c/pages/charity-donation.vue#L10) `thrie` should be `their`. 

Thank you for sharing this project.

**Comment by KodeStar** [comment]
Thanks for pointing this out :) the original had my moms name in it so I just quickly went through and changed those details out, so if you find any more typos feel free to let me know. :)
