### ISSUE TITLE
Way to chronologically arrange picture gallery

### ISSUE THREAD

**Issue by zanaohlala** [Coderior/lovingmemory#3]
Is there a way to name the images files to they show up in a certain order in the gallery?

I'm not too good with JS or nuxt so I'm trying to figure out if this is possible somehow.

Thanks again for such a beautiful project. Beauty things do sometime get born out of sadness.

**Comment by KodeStar** [comment]
They aren't currently ordered in any specific way, I haven't really looked at how they are actually ordered, but it would be possible by filtering the image list, I'll look at ordering by name when I get a chance.

**Comment by KodeStar** [comment]
It looks like it's already ordered lexicographically so if you do image001.jpg image 002.jpg etc it looks like it will work as you want. You need the prefixes otherwise it will go image1.jpg, image11.jpg, image12.jpg image2.jpg image3.jpg etc
