### ISSUE TITLE
Github Pages showing blank page

### ISSUE THREAD

**Issue by mtthidoteu** [Coderior/lovingmemory#5]
Hello there!
Thank you for providing this project. I really appreciate it. I tried following the steps you mentionned and I've succesfully tailored the site! However, I have been unable to properly push it to github pages. I am simply getting a blank page.
Could you have a look? Thank you

URL: https://ken.blackler.eu
Repo: https://github.com/mtthidoteu/kenfuneral

Matt

**Comment by KodeStar** [comment]
You are missing the github workflow from the looks of it - https://github.com/Coderior/lovingmemory/blob/master/.github/workflows/cd.yml

**Comment by KodeStar** [comment]
Also, you don't need to create a CNAME file in the root, the one in the static folder should be used

**Comment by mtthidoteu** [comment]
I think it has something to do with master / main *eyeroll*. By default Github now uses 'main' as the default branch instead of master. I renamed my main branch to master and it now sort of works! 

~~However, now paths aren't working properly and images aren't loading :)~~

WORKS!
